<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <RootNamespace>MineCase.Server</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CodeAnalysisRuleSet>../../build/Analyzers.ruleset</CodeAnalysisRuleSet>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Configurations>Debug;Release;Appveyor;TravisCI</Configurations>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="GameSystems\**" />
    <EmbeddedResource Remove="GameSystems\**" />
    <None Remove="GameSystems\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Physical" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" />
    <PackageReference Include="Microsoft.Orleans.Core" />
    <PackageReference Include="Microsoft.Orleans.Streaming" />
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="All" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="System.Threading.Tasks.Dataflow" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MineCase.Algorithm\MineCase.Algorithm.csproj" />
    <ProjectReference Include="..\MineCase.Core\MineCase.Core.csproj" />
    <ProjectReference Include="..\MineCase.Protocol\MineCase.Protocol.csproj" />
    <ProjectReference Include="..\MineCase.Server.Interfaces\MineCase.Server.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="World\Generation\" />

    <AdditionalFiles Include="..\..\build\stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\MineCase.Protocol\Serialization\BinaryWriterExtensions.cs" Link="BinaryWriterExtensions.cs" />
  </ItemGroup>

</Project>