<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <PropertyGroup>
    <RepositoryUrl>https://github.com/Titlehhhh/McProtoNet</RepositoryUrl>
    <PackageTags>minecraft;protocol;high-performance</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://titlehhhh.github.io/McProtoNet</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>Readme.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <Authors>Titlehhhh</Authors>
    <Copyright>Copyright 2022-$([System.DateTime]::Now.ToString(`yyyy`)) © Titlehhhh</Copyright>
  </PropertyGroup>
  <PropertyGroup>
    <MinVerTagPrefix>v</MinVerTagPrefix>
  </PropertyGroup>
  <ItemGroup Label="PackageIcon">
    <None Include="$(MSBuildThisFileDirectory)/assets/icon.png" Pack="true" Visible="false" PackagePath="" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DotNet.ReproducibleBuilds">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MinVer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <PropertyGroup>
    <EnableSourceLink>true</EnableSourceLink>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <PropertyGroup>
    <NoWarn>$(NoWarn);CS1591;CS0535</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Aspire.Hosting.AppHost" Version="9.4.1" />
    <PackageVersion Include="Aspire.Hosting.MongoDB" Version="9.2.1" />
    <PackageVersion Include="Aspire.Hosting.Testing" Version="9.3.1" />
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />
    <PackageVersion Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.Uris" Version="9.0.0" />
    <PackageVersion Include="Autofac" Version="8.4.0" />
    <PackageVersion Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageVersion Include="CommunityToolkit.Aspire.Hosting.MongoDB.Extensions" Version="9.4.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="4.14.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis" Version="4.13.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Text" Version="4.13.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.14.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.FileProviders.Abstractions" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.FileProviders.Physical" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="9.8.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.ObjectPool" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.ObjectPool.Net40" Version="1.1.0" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="9.4.1" />
    <PackageVersion Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="Microsoft.Orleans.Client" Version="9.1.2" />
    <PackageVersion Include="Microsoft.Orleans.Core" Version="9.1.2" />
    <PackageVersion Include="Microsoft.Orleans.Core.Abstractions" Version="9.1.2" />
    <PackageVersion Include="Microsoft.Orleans.Server" Version="9.1.2" />
    <PackageVersion Include="Microsoft.Orleans.Streaming" Version="9.1.2" />
    <PackageVersion Include="MSTest.TestAdapter" Version="3.8.2" />
    <PackageVersion Include="MSTest.TestFramework" Version="3.8.2" />
    <PackageVersion Include="MongoDB.Bson" Version="3.2.1" />
    <PackageVersion Include="MongoDB.Driver" Version="3.2.1" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.12.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.12.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.12.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.12.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.12.0" />
    <PackageVersion Include="Orleans.Providers.MongoDB" Version="9.1.0" />
    <PackageVersion Include="OrleansDashboard" Version="8.2.0" />
    <PackageVersion Include="Polly" Version="8.6.3" />
    <PackageVersion Include="sharpcompress" Version="0.40.0" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageVersion Include="Stateless" Version="5.19.0" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.1.118" />
    <PackageVersion Include="System.Collections.Immutable" Version="1.4.0" />
    <PackageVersion Include="System.Threading.Tasks.Dataflow" Version="9.0.8" />
    <PackageVersion Include="System.ValueTuple" Version="4.4.0" />
    <PackageVersion Include="Unity.TargetingPack.Modules.2017.2.0f3" Version="1.0.0" />
    <PackageVersion Include="DotNext.IO" Version="5.24.0" />
    <PackageVersion Include="DotNext.Threading" Version="5.24.2" />
    <PackageVersion Include="DotNext" Version="5.24.0" />
    <PackageVersion Include="MinVer" Version="6.0.0" />
    <PackageVersion Include="QuickProxyNet" Version="2.0.0" />
    <PackageVersion Include="ConfigureAwait.Fody" Version="3.3.2" />
    <PackageVersion Include="BouncyCastle.Cryptography" Version="2.5.1" />
    <PackageVersion Include="System.Reactive" Version="6.0.1" />
    <PackageVersion Include="DnsClient" Version="1.8.0" />
    <PackageVersion Include="Tomat.LibDeflate.Native" Version="1.21.1" />
    <PackageVersion Include="System.IO.Pipelines" Version="9.0.2" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageVersion Include="DotNet.ReproducibleBuilds" Version="1.2.25" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.v3" Version="2.0.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net46'">
    <PackageVersion Include="Microsoft.TargetingPack.NETFramework.v4.6" Version="1.0.1" />
  </ItemGroup>
</Project>