<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MineCase</RootNamespace>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CodeAnalysisRuleSet>../../build/Analyzers.ruleset</CodeAnalysisRuleSet>
    <AssemblyName>MineCase.Core</AssemblyName>
    <Configurations>Debug;Release;Appveyor;TravisCI</Configurations>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\MineCase.Nbt\MineCase.Nbt.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Core.Abstractions" />
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="All" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\..\build\stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Game\Entities\" />
    <Folder Include="Game\Entities\" />
  </ItemGroup>

</Project>
