<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

	<ItemGroup>
		<None Remove="obj" />
		<None Remove="bin" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
    <PackageReference Include="AspNetCore.HealthChecks.Uris" />
    <PackageReference Include="Autofac" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Orleans.Server" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Orleans.Providers.MongoDB" />
    <PackageReference Include="OrleansDashboard" />
  </ItemGroup>

  <ItemGroup>
    <None Update=".dockerignore">
      <DependentUpon>Dockerfile</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="*.log;*.txt" />
    <None Remove="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="banned-ips.json" />
    <None Remove="banned-players.json" />
    <None Remove="config.json" />
    <None Remove="ops.json" />
    <None Remove="server.json" />
    <None Remove="whitelist.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\data\crafting.txt" Link="crafting.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\data\furnace.txt" Link="furnace.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="banned-ips.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="banned-players.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="config.docker.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ops.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="server.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="whitelist.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MineCase.Serialization\MineCase.Serialization.csproj" />
    <ProjectReference Include="..\MineCase.Server.Grains\MineCase.Server.Grains.csproj" />
    <ProjectReference Include="..\MineCase.ServiceDefaults\MineCase.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>