<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <AssemblyName>MineCase.Server.Interfaces</AssemblyName>
    <RootNamespace>MineCase.Server</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CodeAnalysisRuleSet>../../build/Analyzers.ruleset</CodeAnalysisRuleSet>
    <Configurations>Debug;Release;Appveyor;TravisCI</Configurations>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="World\Biomes\**" />
    <EmbeddedResource Remove="World\Biomes\**" />
    <None Remove="World\Biomes\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" />
    <PackageReference Include="Microsoft.Orleans.Core" />
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MineCase.Core\MineCase.Core.csproj" />
    <ProjectReference Include="..\MineCase.Protocol\MineCase.Protocol.csproj" />
    <ProjectReference Include="..\MineCase.Server.Engine\MineCase.Server.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Network\Handshaking\" />

    <AdditionalFiles Include="..\..\build\stylecop.json" />

    <Folder Include="Network\Handshaking\" />

    <Folder Include="Play\" />
  </ItemGroup>

</Project>