<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="config.json" />
    <None Remove="OrleansConfiguration.dev.xml" />
    <None Remove="OrleansConfiguration.docker.xml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="OrleansConfiguration.dev.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="OrleansConfiguration.docker.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  
  <ItemGroup>
    <None Remove="*.log;*.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="9.0.8" />
    <PackageReference Include="Microsoft.Orleans.Client" Version="3.3.0" />
    <PackageReference Include="Orleans.MultiClient" Version="3.1.7" />
    <PackageReference Include="Orleans.Providers.MongoDB" Version="3.1.7" />
    <PackageReference Include="Polly" Version="7.2.0" />
    <PackageReference Include="sharpcompress" Version="0.40.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MineCase.Core\MineCase.Core.csproj" />
    <ProjectReference Include="..\MineCase.Protocol\MineCase.Protocol.csproj" />
    <ProjectReference Include="..\MineCase.Server.Interfaces\MineCase.Server.Interfaces.csproj" />
    <ProjectReference Include="..\MineCase.ServiceDefaults\MineCase.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update=".dockerignore">
      <DependentUpon>Dockerfile</DependentUpon>
    </None>
  </ItemGroup>

</Project>