<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="config.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  
  <ItemGroup>
    <None Remove="*.log;*.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" />
    <PackageReference Include="Microsoft.Orleans.Client" />
    <PackageReference Include="Orleans.Providers.MongoDB" />
    <PackageReference Include="Polly" />
    <PackageReference Include="sharpcompress" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MineCase.Core\MineCase.Core.csproj" />
    <ProjectReference Include="..\MineCase.Protocol\MineCase.Protocol.csproj" />
    <ProjectReference Include="..\MineCase.Serialization\MineCase.Serialization.csproj" />
    <ProjectReference Include="..\MineCase.Server.Grains\MineCase.Server.Grains.csproj" />
    <ProjectReference Include="..\MineCase.Server.Interfaces\MineCase.Server.Interfaces.csproj" />
    <ProjectReference Include="..\MineCase.ServiceDefaults\MineCase.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update=".dockerignore">
      <DependentUpon>Dockerfile</DependentUpon>
    </None>
  </ItemGroup>

</Project>